delete from driver_entity;

insert into driver_entity (id, name) values (1, 'Juan Alvarez');
insert into driver_entity (id, name) values (2, 'María Rodríguez');
insert into driver_entity (id, name) values (3, 'Mafe Gómez');
insert into driver_entity (id, name) values (4, 'Carlos Parra');
insert into driver_entity (id, name) values (5, 'Lucas Vega');
insert into driver_entity (id, name) values (6, 'Ana Galindo');
insert into driver_entity (id, name) values (7, 'Juan Hernandez');
insert into driver_entity (id, name) values (8, 'Lucía Mora');
insert into driver_entity (id, name) values (9, 'Elvia García');
insert into driver_entity (id, name) values (10, 'Gustavo Cuellar');
insert into driver_entity (id, name) values (11, 'Rosa Bejarano');
insert into driver_entity (id, name) values (12, 'Lida Trujillo');
insert into driver_entity (id, name) values (13, 'Angela Silva');
insert into driver_entity (id, name) values (14, 'Franklin Gutierrez');
insert into driver_entity (id, name) values (15, 'Lina Toro');
insert into driver_entity (id, name) values (16, 'Andrea Serna');
insert into driver_entity (id, name) values (17, 'Luis Trujillo');
insert into driver_entity (id, name) values (18, 'Elena Marquez');
insert into driver_entity (id, name) values (19, 'Sergio Sierra');
insert into driver_entity (id, name) values (20, 'Nancy Pérez');
